feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
globant:
  client:
    host:
      url: https://www.anapioficeandfire.com/api
